language: node_js
node_js:
  - "node"

script: npm run build

deploy:
  provider: pages
  skip-cleanup: true
  fqdn: "switchblade.xyz"
  github-token: $GITHUB_TOKEN
  local-dir: "dist/"
  keep-history: true
  on:
    branch: master
